In [58]:
# Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
#print(X)
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'median', axis = 0)# mean, median, most_frequent

imputer = imputer.fit(X_train[:, 1:3])
X_train[:, 1:3] = imputer.transform(X_train[:, 1:3])
print(X_train)

imputer = imputer.fit(X_test[:, 1:3])
X_test[:, 1:3] = imputer.transform(X_test[:, 1:3])
print(X_test)

[['Germany' 40.0 61000.0]
 ['France' 37.0 67000.0]
 ['Spain' 27.0 48000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Spain' 38.0 61000.0]
 ['France' 44.0 72000.0]
 ['France' 35.0 58000.0]]
[['Germany' 30.0 54000.0]
 ['Germany' 50.0 83000.0]]


# Encoding categorical data

In [59]:
# Encoding the Independent Variable

In [60]:
#1. LabelEncoding : 
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
#labelencoder_X.fit_transform(X[:, 0])
X_train[:, 0] = labelencoder_X.fit_transform(X_train[:, 0])
print(X_train[:, 0])
X_test[:, 0] = labelencoder_X.fit_transform(X_test[:, 0])
print(X_test[:, 0])

[1 0 2 2 0 2 0 0]
[0 0]


In [61]:
#2.OneHotEncoder :
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
#X = onehotencoder.fit_transform(X)
X_train = onehotencoder.fit_transform(X_train).toarray()
print(X_train)

[[0.0e+00 1.0e+00 0.0e+00 4.0e+01 6.1e+04]
 [1.0e+00 0.0e+00 0.0e+00 3.7e+01 6.7e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.7e+01 4.8e+04]
 [0.0e+00 0.0e+00 1.0e+00 3.8e+01 5.2e+04]
 [1.0e+00 0.0e+00 0.0e+00 4.8e+01 7.9e+04]
 [0.0e+00 0.0e+00 1.0e+00 3.8e+01 6.1e+04]
 [1.0e+00 0.0e+00 0.0e+00 4.4e+01 7.2e+04]
 [1.0e+00 0.0e+00 0.0e+00 3.5e+01 5.8e+04]]


In [62]:
X_train=X_train[:,1:]
print(X_train)

[[1.0e+00 0.0e+00 4.0e+01 6.1e+04]
 [0.0e+00 0.0e+00 3.7e+01 6.7e+04]
 [0.0e+00 1.0e+00 2.7e+01 4.8e+04]
 [0.0e+00 1.0e+00 3.8e+01 5.2e+04]
 [0.0e+00 0.0e+00 4.8e+01 7.9e+04]
 [0.0e+00 1.0e+00 3.8e+01 6.1e+04]
 [0.0e+00 0.0e+00 4.4e+01 7.2e+04]
 [0.0e+00 0.0e+00 3.5e+01 5.8e+04]]


In [66]:
X_test = onehotencoder.fit_transform(X_test).toarray()
print(X_test)

[[1.0e+00 0.0e+00 5.4e+04]
 [0.0e+00 1.0e+00 8.3e+04]]


In [67]:
X_test=X_test[:,1:]
print(X_test)

[[0.0e+00 5.4e+04]
 [1.0e+00 8.3e+04]]


In [69]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
#X_test = sc_X.transform(X_test)
print(X_train)
#print(X_test)

[[ 2.64575131 -0.77459667  0.27978024 -0.13108063]
 [-0.37796447 -0.77459667 -0.23673712  0.49810638]
 [-0.37796447  1.29099445 -1.95846165 -1.49431914]
 [-0.37796447  1.29099445 -0.06456467 -1.07486114]
 [-0.37796447 -0.77459667  1.65715986  1.75648039]
 [-0.37796447  1.29099445 -0.06456467 -0.13108063]
 [-0.37796447 -0.77459667  0.96847005  1.02242888]
 [-0.37796447 -0.77459667 -0.58108203 -0.44567413]]
