In [2]:
# Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Data.csv')
#print(dataset)
print(dataset.head(2))
X = dataset.iloc[:, :-1].values
#X = dataset.drop('Purchased',axis='columns')
#X = dataset.iloc[:, :-1]
y = dataset.iloc[:, 3].values
#y = dataset.iloc[:, 3]
print("---------Feature Matrix : X -------------\n")
print(X)
print("---------Feature Vector : y -------------\n")
print(y)

# Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'median', axis = 0)# mean, median, most_frequent

imputer = imputer.fit(X[:, 1:3])
X[:, 1:3]=imputer.transform(X[:, 1:3])
print("--------- After Handling Missing Values -------------\n")
print(X)


  Country   Age   Salary Purchased
0  France  44.0  72000.0        No
1   Spain  27.0  48000.0       Yes
---------Feature Matrix : X -------------

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
---------Feature Vector : y -------------

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
--------- After Handling Missing Values -------------

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [3]:
#print("---------  Manually Hangling Missing Values-------------\n")
Age=dataset.Age
Age=dataset['Age']
#print(Age)
Salary=dataset['Salary']
#print(Salary)
#print(np.mean(Salary))
dataset.Salary.median()
dataset.Age.median()
#dataset.Age = dataset.Age.fillna(dataset.Age.median())
#dataset['Age'] = dataset.Age.fillna(dataset.Age.median())
#dataset.Salary = dataset.Salary.fillna(dataset.Salary.median())

38.0

In [12]:
#1. LabelEncoding : 
print(X)
print(X[:, 0])
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
# Label Encoding : Features Matrix-X
#labelencoder_X.fit_transform(X[:, 0])
X[:, 0]=labelencoder_X.fit_transform(X[:, 0])

print(X)
print(X[:, 0])

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['France' 'Spain' 'Germany' 'Spain' 'Germany' 'France' 'Spain' 'France'
 'Germany' 'France']
[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 61000.0]
 [0 35.0 58000.0]
 [2 38.0 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]
[0 2 1 2 1 0 2 0 1 0]


In [44]:
# Label Encoding : Features Vector-y
print(y)
labelencoder_y = LabelEncoder()
y=labelencoder_y.fit_transform(y)
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
[0 1 0 0 1 1 0 1 0 1]


In [13]:
#2.OneHotEncoder :
print(X)
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
#X = onehotencoder.fit_transform(X)
X=onehotencoder.fit_transform(X).toarray()
print(X)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 61000.0]
 [0 35.0 58000.0]
 [2 38.0 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]
[[1.0e+00 0.0e+00 0.0e+00 4.4e+01 7.2e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.7e+01 4.8e+04]
 [0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]
 [0.0e+00 0.0e+00 1.0e+00 3.8e+01 6.1e+04]
 [0.0e+00 1.0e+00 0.0e+00 4.0e+01 6.1e+04]
 [1.0e+00 0.0e+00 0.0e+00 3.5e+01 5.8e+04]
 [0.0e+00 0.0e+00 1.0e+00 3.8e+01 5.2e+04]
 [1.0e+00 0.0e+00 0.0e+00 4.8e+01 7.9e+04]
 [0.0e+00 1.0e+00 0.0e+00 5.0e+01 8.3e+04]
 [1.0e+00 0.0e+00 0.0e+00 3.7e+01 6.7e+04]]


In [15]:
X=X[:,1:]
print(X)

[[-0.65465367 -0.65465367  0.76973439  0.77256767]
 [-0.65465367  1.52752523 -1.69922498 -1.40879986]
 [ 1.52752523 -0.65465367 -1.26352627 -0.86345798]
 [-0.65465367  1.52752523 -0.10166303 -0.22722578]
 [ 1.52752523 -0.65465367  0.18880278 -0.22722578]
 [-0.65465367 -0.65465367 -0.53736175 -0.49989673]
 [-0.65465367  1.52752523 -0.10166303 -1.04523861]
 [-0.65465367 -0.65465367  1.35066601  1.40879986]
 [ 1.52752523 -0.65465367  1.64113182  1.77236112]
 [-0.65465367 -0.65465367 -0.24689594  0.3181161 ]]


In [16]:
# Feature Scaling : Feature Matrix - X
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)
print(X)

[[-0.65465367 -0.65465367  0.76973439  0.77256767]
 [-0.65465367  1.52752523 -1.69922498 -1.40879986]
 [ 1.52752523 -0.65465367 -1.26352627 -0.86345798]
 [-0.65465367  1.52752523 -0.10166303 -0.22722578]
 [ 1.52752523 -0.65465367  0.18880278 -0.22722578]
 [-0.65465367 -0.65465367 -0.53736175 -0.49989673]
 [-0.65465367  1.52752523 -0.10166303 -1.04523861]
 [-0.65465367 -0.65465367  1.35066601  1.40879986]
 [ 1.52752523 -0.65465367  1.64113182  1.77236112]
 [-0.65465367 -0.65465367 -0.24689594  0.3181161 ]]


In [23]:
# Feature Scaling : Feature Vector - y
'''print(y)
from sklearn.preprocessing import StandardScaler
sc_y = StandardScaler()
y=y.reshape(-1, 1)
print(y)
y = sc_y.fit_transform(y)
print(y)'''

'print(y)\nfrom sklearn.preprocessing import StandardScaler\nsc_y = StandardScaler()\ny=y.reshape(-1, 1)\nprint(y)\ny = sc_y.fit_transform(y)\nprint(y)'

In [24]:
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split - old
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [25]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[-0.65465367 -0.65465367 -0.24689594  0.3181161 ]
 [-0.65465367  1.52752523 -1.69922498 -1.40879986]
 [-0.65465367  1.52752523 -0.10166303 -1.04523861]
 [-0.65465367 -0.65465367  1.35066601  1.40879986]
 [-0.65465367  1.52752523 -0.10166303 -0.22722578]
 [-0.65465367 -0.65465367  0.76973439  0.77256767]
 [-0.65465367 -0.65465367 -0.53736175 -0.49989673]]
[[ 1.52752523 -0.65465367 -1.26352627 -0.86345798]
 [ 1.52752523 -0.65465367  1.64113182  1.77236112]
 [ 1.52752523 -0.65465367  0.18880278 -0.22722578]]
[1 1 0 1 0 0 1]
[0 0 1]


# LogisticRegression

In [26]:
from sklearn.linear_model import LogisticRegression 
classifier = LogisticRegression(random_state = 0) 
classifier.fit(X_train, y_train) 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [27]:
y_pred = classifier.predict(X_test) 

In [28]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, y_pred) 
print ("Confusion Matrix : \n", cm) 

Confusion Matrix : 
 [[1 1]
 [0 1]]


In [30]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred)) 

Accuracy :  0.6666666666666666


# SVC

In [31]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train, y_train) 

y_pred = svm.predict(X_test) 
cm = confusion_matrix(y_test, y_pred) 
print ("Confusion Matrix : \n", cm)

print('Accuracy of SVM classifier on training set: {:.2f}'
     .format(svm.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.2f}'
     .format(svm.score(X_test, y_test)))

Confusion Matrix : 
 [[0 2]
 [0 1]]
Accuracy of SVM classifier on training set: 0.86
Accuracy of SVM classifier on test set: 0.33


# Decision Tree Classifier

In [32]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train, y_train)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 1.00
Accuracy of Decision Tree classifier on test set: 0.00
