In [9]:
from sklearn.metrics import confusion_matrix, classification_report

In [10]:
C="Cat"
D="Dog"

In [11]:
#Actual Values
y_true=[C,C,C,C,C,C,D,D,D,D]
#Predicted Values
y_pred=[C,C,C,C,D,D,D,D,D,C]

In [12]:
#PRINT THE CONFUSION MATRIX
cm=confusion_matrix(y_true, y_pred)
print(cm)

[[4 2]
 [1 3]]


In [14]:
#PRINT THE CLASSIFICATION REPORT - PRECISION, RECALL
cr=classification_report(y_true, y_pred,digits=2)
print(cr)

             precision    recall  f1-score   support

        Cat       0.80      0.67      0.73         6
        Dog       0.60      0.75      0.67         4

avg / total       0.72      0.70      0.70        10



# Confusion Matrix : Performance Metrics MultiClass Classification Problem

In [17]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score, f1_score,precision_recall_fscore_support

In [18]:
C="Cat"
D="Dog"
F="Fox"

In [19]:
#Actual Values
y_true=[C,C,C,C,C,C,D,D,D,D,D,D,D,D,D,D,F,F,F,F,F,F,F,F,F]
#Predicted Values
y_pred=[C,C,C,C,D,F,C,C,C,C,C,C,D,D,F,F,C,C,C,D,D,D,D,D,D]

In [103]:
#PRINT THE CONFUSION MATRIX
cm=metrics.confusion_matrix(y_true, y_pred)
print(cm)

[[4 1 1]
 [6 2 2]
 [3 6 0]]


In [104]:
#PRINT THE CLASSIFICATION REPORT - PRECISION, RECALL
cr=metrics.classification_report(y_true, y_pred,digits=3)
print(cr)

             precision    recall  f1-score   support

        Cat      0.308     0.667     0.421         6
        Dog      0.222     0.200     0.211        10
        Fox      0.000     0.000     0.000         9

avg / total      0.163     0.240     0.185        25



# Confusion Matrix : Spam Detection

In [105]:
#from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report,precision_score, recall_score,f1_score,precision_recall_fscore_support

In [106]:
S="Spam"
M="Not Spam"

In [107]:
y_true=[M,M,M,M,M,M,S,S,S,S]
y_pred=[M,M,M,M,S,S,S,S,S,M]

In [108]:
P="Not Spam"
N="Spam"
y_true=[P,P,P,P,P,P,N,N,N,N]
y_pred=[P,P,P,P,N,N,P,N,N,N]

In [109]:
#PRINT THE CONFUSION MATRIX
cm=confusion_matrix(y_true, y_pred)
print(cm)

[[4 2]
 [1 3]]


In [110]:
#PRINT THE CLASSIFICATION REPORT - PRECISION, RECALL
cr=classification_report(y_true, y_pred,digits=3)
print(cr)

             precision    recall  f1-score   support

   Not Spam      0.800     0.667     0.727         6
       Spam      0.600     0.750     0.667         4

avg / total      0.720     0.700     0.703        10



# Confusion Matrix : Cancer or HIV or Codid or Fire Alarm or Stock  Crash

In [111]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix as cm, classification_report as cr, cohen_kappa_score as cks

In [112]:
P="HIV Positive" 
N="Hiv Negative" 

In [113]:
y_true=[P,P,P,P,P,P,N,N,N,N]
y_pred=[P,P,P,P,N,N,P,N,N,N]

In [114]:
#PRINT THE CONFUSION MATRIX
cm=cm(y_true, y_pred)
print(cm)

[[4 2]
 [1 3]]


In [115]:
#PRINT THE CLASSIFICATION REPORT - PRECISION, RECALL
cr=cr(y_true, y_pred,digits=3)
print(cr)

              precision    recall  f1-score   support

HIV Positive      0.800     0.667     0.727         6
Hiv Negative      0.600     0.750     0.667         4

 avg / total      0.720     0.700     0.703        10



kappa : float

ohen’s kappa is a useful evaluation metric when dealing with imbalanced data.

The kappa statistic, which is a number between -1 and 1. 

The maximum value means complete agreement; zero or lower means chance agreement.

In [22]:
from sklearn.metrics import  cohen_kappa_score as cks
#The Kohen Kappa Score
y_true = [P,P,P,N]
y_pred = [P,P,P,P]
cks=cks(y_true, y_pred)
print(cks)

NameError: name 'P' is not defined

# Compute Receiver operating characteristic (ROC).

In [145]:
#sklearn.metrics.roc_curve
import numpy as np
from sklearn.metrics import roc_curve,auc
from sklearn.metrics import roc_auc_score

from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier

In [144]:
y = np.array([1, 1, 2, 2])
scores = np.array([0.1, 0.4, 0.35, 0.8])
#y = [1, 1, 2, 2]
#scores = [0.1, 0.4, 0.35, 0.8]
y

array([1, 1, 2, 2])

In [138]:
fpr, tpr, thresholds = roc_curve(y, scores, pos_label=2)

In [139]:
fpr

array([0. , 0.5, 0.5, 1. ])

In [140]:
tpr

array([0.5, 0.5, 1. , 1. ])

In [141]:
thresholds

array([0.8 , 0.4 , 0.35, 0.1 ])